# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(1040, 850)
        self.label = QtWidgets.QLabel(About)
        self.label.setGeometry(QtCore.QRect(250, 230, 741, 421))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.answer = QtWidgets.QPushButton(About)
        self.answer.setGeometry(QtCore.QRect(60, 210, 181, 221))
        self.answer.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.answer.setIcon(icon)
        self.answer.setIconSize(QtCore.QSize(200, 200))
        self.answer.setObjectName("answer")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "关于"))
        self.label.setText(_translate("About", "<html><head/><body><p align=\"justify\">*大学排名数据来源于<a href=\"https://www.shanghairanking.cn/\"><span style=\" text-decoration: underline; color:#0000ff;\">软科排名</span></a></p><p align=\"justify\">*导师信息来自于各大学官网</p><p align=\"justify\">*GUI实现通过PyQt5库实现</p><p align=\"justify\">*数据通过requests爬虫得到</p><p align=\"justify\">*sqlite3数据库储存</p><p align=\"justify\"><br/></p><p align=\"justify\"><br/></p><p align=\"justify\"><br/></p><p align=\"right\">editor: Jerry Xiao</p><p align=\"justify\"><br/></p><p align=\"justify\"><br/></p><p align=\"justify\"><br/></p></body></html>"))
