# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chem_rank.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Chem_Rank(object):
    def setupUi(self, Chem_Rank):
        Chem_Rank.setObjectName("Chem_Rank")
        Chem_Rank.resize(1040, 850)
        self.tableWidget = QtWidgets.QTableWidget(Chem_Rank)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 1021, 801))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(500)
        self.label = QtWidgets.QLabel(Chem_Rank)
        self.label.setGeometry(QtCore.QRect(410, 10, 221, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Chem_Rank)
        self.comboBox.setGeometry(QtCore.QRect(936, 10, 91, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(Chem_Rank)
        self.label_2.setGeometry(QtCore.QRect(880, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Chem_Rank)
        QtCore.QMetaObject.connectSlotsByName(Chem_Rank)

    def retranslateUi(self, Chem_Rank):
        _translate = QtCore.QCoreApplication.translate
        Chem_Rank.setWindowTitle(_translate("Chem_Rank", "化学学科大学排名"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Chem_Rank", "学校名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Chem_Rank", "层次/地区"))
        self.label.setText(_translate("Chem_Rank", "化学学科大学排名"))
        self.comboBox.setItemText(0, _translate("Chem_Rank", "中国"))
        self.comboBox.setItemText(1, _translate("Chem_Rank", "世界"))
        self.label_2.setText(_translate("Chem_Rank", "地区："))
