# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cn_rank.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cn_Rank(object):
    def setupUi(self, Cn_Rank):
        Cn_Rank.setObjectName("Cn_Rank")
        Cn_Rank.resize(1040, 850)
        self.tableWidget = QtWidgets.QTableWidget(Cn_Rank)
        self.tableWidget.setGeometry(QtCore.QRect(0, 50, 1035, 790))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(257)
        self.comboBox = QtWidgets.QComboBox(Cn_Rank)
        self.comboBox.setGeometry(QtCore.QRect(940, 10, 91, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(Cn_Rank)
        self.label.setGeometry(QtCore.QRect(420, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Cn_Rank)
        self.label_2.setGeometry(QtCore.QRect(890, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Cn_Rank)
        QtCore.QMetaObject.connectSlotsByName(Cn_Rank)

    def retranslateUi(self, Cn_Rank):
        _translate = QtCore.QCoreApplication.translate
        Cn_Rank.setWindowTitle(_translate("Cn_Rank", "中国大学排名"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Cn_Rank", "学校名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Cn_Rank", "类型"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Cn_Rank", "等级"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Cn_Rank", "地区"))
        self.comboBox.setItemText(0, _translate("Cn_Rank", "2021"))
        self.comboBox.setItemText(1, _translate("Cn_Rank", "2020"))
        self.comboBox.setItemText(2, _translate("Cn_Rank", "2019"))
        self.comboBox.setItemText(3, _translate("Cn_Rank", "2018"))
        self.comboBox.setItemText(4, _translate("Cn_Rank", "2017"))
        self.comboBox.setItemText(5, _translate("Cn_Rank", "2016"))
        self.comboBox.setItemText(6, _translate("Cn_Rank", "2015"))
        self.label.setText(_translate("Cn_Rank", "中国大学排名"))
        self.label_2.setText(_translate("Cn_Rank", "年份："))
