# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(1040, 850)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainPage.setFont(font)
        MainPage.setAutoFillBackground(False)
        MainPage.setStyleSheet("border-image: url(background.png)")
        self.background = QtWidgets.QPushButton(MainPage)
        self.background.setGeometry(QtCore.QRect(210, 0, 701, 531))
        self.background.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("background.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.background.setIcon(icon)
        self.background.setIconSize(QtCore.QSize(1000, 1000))
        self.background.setObjectName("background")
        self.verticalLayoutWidget = QtWidgets.QWidget(MainPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 210, 61, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cnRank_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cnRank_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("finger.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cnRank_button.setIcon(icon1)
        self.cnRank_button.setIconSize(QtCore.QSize(40, 40))
        self.cnRank_button.setObjectName("cnRank_button")
        self.verticalLayout.addWidget(self.cnRank_button)
        self.worldRank_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.worldRank_button.setText("")
        self.worldRank_button.setIcon(icon1)
        self.worldRank_button.setIconSize(QtCore.QSize(40, 40))
        self.worldRank_button.setObjectName("worldRank_button")
        self.verticalLayout.addWidget(self.worldRank_button)
        self.chemRank_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.chemRank_button.setText("")
        self.chemRank_button.setIcon(icon1)
        self.chemRank_button.setIconSize(QtCore.QSize(40, 40))
        self.chemRank_button.setObjectName("chemRank_button")
        self.verticalLayout.addWidget(self.chemRank_button)
        self.teacher_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.teacher_button.setText("")
        self.teacher_button.setIcon(icon1)
        self.teacher_button.setIconSize(QtCore.QSize(40, 40))
        self.teacher_button.setObjectName("teacher_button")
        self.verticalLayout.addWidget(self.teacher_button)
        self.label = QtWidgets.QLabel(MainPage)
        self.label.setGeometry(QtCore.QRect(210, 580, 681, 131))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")



        self.retranslateUi(MainPage)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "主页"))
        self.label.setText(_translate("MainPage", "大学排名与导师查询系统"))
