# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacher.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Teacher(object):
    def setupUi(self, Teacher):
        Teacher.setObjectName("Teacher")
        Teacher.resize(1040, 850)
        self.tableWidget = QtWidgets.QTableWidget(Teacher)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 1031, 801))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(255)
        self.label = QtWidgets.QLabel(Teacher)
        self.label.setGeometry(QtCore.QRect(440, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Teacher)
        QtCore.QMetaObject.connectSlotsByName(Teacher)

    def retranslateUi(self, Teacher):
        _translate = QtCore.QCoreApplication.translate
        Teacher.setWindowTitle(_translate("Teacher", "导师查询"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Teacher", "学校"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Teacher", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Teacher", "职称"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Teacher", "研究方向"))
        self.label.setText(_translate("Teacher", "导师信息查询"))
