# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'world_rank.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_World_Rank(object):
    def setupUi(self, World_Rank):
        World_Rank.setObjectName("World_Rank")
        World_Rank.resize(1040, 850)
        self.tableWidget = QtWidgets.QTableWidget(World_Rank)
        self.tableWidget.setGeometry(QtCore.QRect(0, 60, 1035, 790))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(343)
        self.label = QtWidgets.QLabel(World_Rank)
        self.label.setGeometry(QtCore.QRect(420, 0, 191, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(World_Rank)
        self.comboBox.setGeometry(QtCore.QRect(930, 20, 91, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(World_Rank)
        self.label_2.setGeometry(QtCore.QRect(880, 20, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(World_Rank)
        QtCore.QMetaObject.connectSlotsByName(World_Rank)

    def retranslateUi(self, World_Rank):
        _translate = QtCore.QCoreApplication.translate
        World_Rank.setWindowTitle(_translate("World_Rank", "世界大学排名"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("World_Rank", "学校名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("World_Rank", "国家"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("World_Rank", "国家/地区排名"))
        self.label.setText(_translate("World_Rank", " 世界大学排名"))
        self.comboBox.setItemText(0, _translate("World_Rank", "2020"))
        self.comboBox.setItemText(1, _translate("World_Rank", "2019"))
        self.comboBox.setItemText(2, _translate("World_Rank", "2018"))
        self.comboBox.setItemText(3, _translate("World_Rank", "2017"))
        self.comboBox.setItemText(4, _translate("World_Rank", "2016"))
        self.comboBox.setItemText(5, _translate("World_Rank", "2015"))
        self.comboBox.setItemText(6, _translate("World_Rank", "2014"))
        self.comboBox.setItemText(7, _translate("World_Rank", "2013"))
        self.comboBox.setItemText(8, _translate("World_Rank", "2012"))
        self.comboBox.setItemText(9, _translate("World_Rank", "2011"))
        self.comboBox.setItemText(10, _translate("World_Rank", "2010"))
        self.label_2.setText(_translate("World_Rank", "年份："))
